PEG1 CMR beta calculation
===============================================================

##### Analyst: Samantha Schaffner
##### Date: Mar 2, 2023

Update Apr 18, 2023: Use individuals matched with MatchIt 4.5.3, probit link function.

### Libraries
```{r libraries, eval=F}
setwd("/home1/NEURO/schaffner")
library(ggplot2) #For plotting
library(dplyr)
library(reshape2)
library(gridExtra)
library(limma)
library(comeback)
library(car)
```

## Load meta data and betas

### males
```{r load data, eval=F}
load("~/4-replication/Chuang_2017/preprocessing/PEG1_betas_combat.RData")

#Meta data
meta_M <- read.csv("~/4-replication/Chuang_2017/validation_matched/male/TERRE_PEG1_meta_M_matched_probit.csv")
meta_M_PEG1 <- meta_M[meta_M$cohort=="PEG1",]

summary(as.factor(meta_M_PEG1$PD))
#   Case Control 
#     56      62

#subset betas
dim(betas_M <- betas_combat[,colnames(betas_combat) %in% meta_M_PEG1$Sample_Name]) # 424263    118
```

## Calculating CMR median betas

Using pre-defined blood reference CMRs. 

### males
```{r CoMeBack F, eval=F}
betas_M_t <- t(betas_M)

#get reference CMRs (1k)
load("~/4-replication/Chuang_2017/validation_matched/refCMRs_in_PEG1.RData")

# use uncorrrected betas to calculate CMR median betas
# with this function from the package, an error "Error in Mdata[,x]: index type "list" is incorrect" occurs.  Looking at cmr_comp, line 22 specifies to unlist all the CMRs into one vector (as opposed to a list of lists containing CMRs per chromosome) only if there are fewer than 24 chromosomes. 

#I have 24 exactly, and it seems like the CMRs need to be unlisted for the next part of the function to work. I commented out this line and saved a new R script, "cmr_comp2.R," which I will try on my data.
source("/home1/NEURO/schaffner/2-EWAS_CMRs/cmr_comp2.R")

refCMR_medB_M=cmr_comp2(cmrs = refCMRlist, Mdata = betas_M_t, cmethod="median")
save(refCMR_medB_M, file="/home1/NEURO/schaffner/4-replication/Chuang_2017/validation_matched/male/PEG1_matched_with_TERRE_refCMR_medB_M_v4.RData")
```

