plink: "~/plink"
plink2: "~/plink2"
flashpca: "~/flashpca_x86-64"
bcftools: "~/miniconda3/envs/snakemake/bin/bcftools"
tabix: "~/miniconda3/envs/snakemake/bin/tabix"
kg_data: "~/1000G_plink/all_phase3_biallelic_autosome"
kg_panel: "~/1000G_plink/integrated_call_samples_v3.20130502.ALL.panel"
kg_vars: "~/1000G_plink/ALL.wgs.phase3_shapeit2_mvncall_integrated_v5b.20130502.sites.vcf.gz"
LD: "~/regions_to_exclude/longrange_ld.txt"
mhc: "~/regions_to_exclude/mhc_region.txt"
hg19: "~/human_g1k_v37.fasta"
threads: "20"
